matrix:
  include:
    - name: "macOS 10.10"
      os: osx
      osx_image: xcode6.4
      language: generic
    - name: "macOS 10.11"
      os: osx
      osx_image: xcode8
      language: generic
    - name: "macOS 10.13"
      os: osx
      osx_image: xcode9.4
      language: generic
    - name: "Flatpak"
      os: linux
      dist: xenial
      sudo: required
      language: generic

script:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then .travisci/test_macos.sh ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .travisci/test_flatpak.sh ; fi
