[tool.poetry]
name = "quodlibet"
version = "4.7.0-pre"
description = "A music library, tagger, and player"
authors = ["Joe Wreschnig", "Michael Urman", "Steven Robertson",
    "Christoph Reiter", "Nick Boultbee", "(many others)"]
maintainers = ["Christoph Reiter"]
homepage = "https://quodlibet.readthedocs.io/"
documentation = "https://quodlibet.readthedocs.io/"
repository = "https://github.com/quodlibet/quodlibet"
keywords = ["audio", "music", "player", "tags", "gtk"]
license = "GPL-2.0-or-later"

packages = [
    { include = "quodlibet", from = "." }
]

[tool.poetry.scripts]
# Convenience: `poetry run quodlibet` just runs the app (with no CLI args)
quodlibet = "quodlibet.main:main"


[tool.poetry.dependencies]
python = "^3.10"
mutagen = "^1.45"
feedparser = "^5.2 || ^6.0"
pycairo = "^1.19"
pygobject = "^3.34.0"
# Optional (mainly plugins)
musicbrainzngs = { version = "0.*", optional = true }
dbus-python = { version = "*", platform="linux", optional = true }
# 0.28 switched to lxml which is proving tricky on Windows
soco = { version = ">=0.27, <0.28", optional = true }
pypresence = { version = "^4.2.1", optional = true }
paho-mqtt = { version = "^1.6.1", optional = true }

[tool.poetry.extras]
# Use with poetry install -E plugins
plugins = ["musicbrainzngs", "dbus-python", "paho-mqtt", "soco", "pypresence"]

[tool.poetry.dev-dependencies]
pytest = '^7.2.2'
polib = '^1.2.0'
sphinx = '^6.1.3'
sphinx_rtd_theme = '^1.2.0'
sphinx-autobuild = "^2021.3.14"
flake8 = "^6.0.0"
coverage = { extras = ["toml"], version = "^7.2.1" }
mypy = "1.5.1"
flaky = "^3.7.0"
types-docutils = "^0.19.0"
types-certifi = "^2021.10.8.3"
types-requests = "^2.28.11.15"
pyvirtualdisplay = { version = "^3.0", platform = "linux" }
setuptools = "^68.1.2"

[tool.coverage.run]
omit = ["quodlibet/packages/*"]
include = ["quodlibet/*"]

[build-system]
requires = ["setuptools", "wheel"]
