# action.yml
name: Fedora 33
description: Run tests for Fedora 33
runs:
  using: docker
  image: Dockerfile
  run: |
      poetry config virtualenvs.in-project true
      poetry install -E plugins
      PYTEST_ADDOPTS=-rxXs python3 setup.py test
