name: "test-nix"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-nix-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: workflow/nix-shell-action@v3
        with:
          flakes: .#
          script: |
            nix run poetry --version
            nix flake check
